export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL';

export const PRODUCT_DETAIL_REQUEST = 'PRODUCT_DETAIL_REQUEST';
export const PRODUCT_DETAIL_SUCCESS = 'PRODUCT_DETAIL_SUCCESS';
export const PRODUCT_DETAIL_FAIL = 'PRODUCT_DETAIL_FAIL';

export const PRODUCT_LISTCART_REQUEST = 'PRODUCT_LISTCART_REQUEST';
export const PRODUCT_LISTCART_SUCCESS = 'PRODUCT_LISTCART_SUCCESS';
export const PRODUCT_LISTCART_FAIL = 'PRODUCT_LISTCART_FAIL';

export const PRODUCT_CART_REQUEST = 'PRODUCT_CART_REQUEST';
export const PRODUCT_CART_SUCCESS = 'PRODUCT_CART_SUCCESS';
export const PRODUCT_CART_FAIL = 'PRODUCT_CART_FAIL';
